### ISSUE TITLE
Countdown timer for tasks

### ISSUE THREAD

**Issue by SparrowMike** [SparrowMike/WorkWise#4]
This actually needs more examples of the vibe of the extension but adding it here as I have seen cool clock 

https://codepen.io/bsmith/pen/QWRLye

**Comment by SparrowMike** [comment]
Can rename this issue to what been discussed - have a timeout if each new added task the clock can be moved to mood boards ideas

**Comment by MohdSaifulM** [comment]
@SparrowMike I merged the color transition for the blob. Am working on the rest of the stuff i.e to sync the time left with the pop up 🥲

**Comment by SparrowMike** [comment]
Ok, thanks @MohdSaifulM - many problems with this issue, should we break it down to few issues or have one big issue with listed subtasks?

**Comment by SparrowMike** [comment]
Add stop/restart buttons ?
