### ISSUE TITLE
improve build process for faster development

### ISSUE THREAD

**Issue by SparrowMike** [SparrowMike/WorkWise#8]
- webpack is integrated and will compile entire code whenever any changes are made

Something to look into - do we actually need sass to build from package.json? currently i implemented webpack to do so, I guess it will only be needed if we need another instance of react running as a separate application

Also vite doesn't seem to be working anymore - this all could possible be clean up

No we DO NOT - scrap all vite - cleanup package.json

**Comment by SparrowMike** [comment]
considerations for webpack

https://stackoverflow.com/questions/49348365/webpack-4-size-exceeds-the-recommended-limit-244-kib

**Comment by SparrowMike** [comment]
Need to look in into force refresh on the content file as currently it's still required to refresh the extension and then the page itself

**Comment by MohdSaifulM** [comment]
I can look into this as well

**Comment by SparrowMike** [comment]
thanks @MohdSaifulM, just pushed a fixed, can test and refactor if needed - closing as works on my side
